[package]
name = "tugtool-rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust language support for tugtool (placeholder)"

[dependencies]

[lints]
workspace = true
