[package]
name = "tugtool-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Python language support for tugtool using LibCST"

[dependencies]

[lints]
workspace = true
